# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yaml and/or the recipe/meta.yaml.

language: objective-c

env:
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "CRmUIHuaDTcL53G0KuYHEdqJc40ELkkaSCc/YG1q1tY5klrE2FR1hUXm/86O1lxV9zYZBGSIGerTgASV0eG5LYejYEcnPdz3xreV+hhL6/5tIgFZVaNCRwhAQFTDS/PXgxkEksxiof3G5+3X2o/HRZUw7bWeLZz8o3DXTzHG63NuQ6r/5mW4dJ8HVXjAn+sT+QXjZzeN+l+2/FWTooMl+zeY9sgqtkvrPOQH+rQm781jMY63mZ1rlN7hurxWff7Tl3/8oX5/ixM2V69BfQJRPI9ZocKoqO7mnzkn5W+eIH7lxi8MTTs4vPi8VqYr8gNDykc0dpfAKfmIzCwKn17DV6BzrptGMlBcrR40PJeqcR0RELhrGdi5m9OIS7u718qWjUKFNpeybvaMZVWCgZ+mXaI8/RZe2OQbRcPaQNUe0fXhRZlUTAnOyeUxQJcaJcAs6qeAcF73DKVL1YZdCvqK/Xvg7NQmN+g/SmN/RoUAclsNDTY/pVwLuNUylf+KZAWU1/skZzO0A6kdvRBzpmPOLyfF6jF5/KheDRROC2OpzUE1OWb6kRUfVBhjDC3qsInGGqDHRykVwGv9/8maqVzSiM5l6fuUAvbvsm1oPi4qw5ePcJe/iJmrv4FpD18mbu/Dd6Ry13dad1ikxBo2ctCBtCiVXGXrPu6WWTcx1WrI1os="


before_install:
    # Remove homebrew.
    - brew remove --force $(brew list)
    - brew cleanup -s
    - rm -rf $(brew --cache)

install:
    - |
      MINICONDA_URL="http://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      export PATH=/Users/travis/miniconda3/bin:$PATH

      conda config --set show_channel_urls true
      conda update --yes conda
      conda install --yes conda-build=1.20.0 jinja2 anaconda-client
      conda config --add channels conda-forge
      

script:
  - conda build ./recipe

after_success:

  - ./ci_support/upload_or_check_non_existence.py ./recipe conda-forge --channel=main
