travis:
  secure:
    BINSTAR_TOKEN: CRmUIHuaDTcL53G0KuYHEdqJc40ELkkaSCc/YG1q1tY5klrE2FR1hUXm/86O1lxV9zYZBGSIGerTgASV0eG5LYejYEcnPdz3xreV+hhL6/5tIgFZVaNCRwhAQFTDS/PXgxkEksxiof3G5+3X2o/HRZUw7bWeLZz8o3DXTzHG63NuQ6r/5mW4dJ8HVXjAn+sT+QXjZzeN+l+2/FWTooMl+zeY9sgqtkvrPOQH+rQm781jMY63mZ1rlN7hurxWff7Tl3/8oX5/ixM2V69BfQJRPI9ZocKoqO7mnzkn5W+eIH7lxi8MTTs4vPi8VqYr8gNDykc0dpfAKfmIzCwKn17DV6BzrptGMlBcrR40PJeqcR0RELhrGdi5m9OIS7u718qWjUKFNpeybvaMZVWCgZ+mXaI8/RZe2OQbRcPaQNUe0fXhRZlUTAnOyeUxQJcaJcAs6qeAcF73DKVL1YZdCvqK/Xvg7NQmN+g/SmN/RoUAclsNDTY/pVwLuNUylf+KZAWU1/skZzO0A6kdvRBzpmPOLyfF6jF5/KheDRROC2OpzUE1OWb6kRUfVBhjDC3qsInGGqDHRykVwGv9/8maqVzSiM5l6fuUAvbvsm1oPi4qw5ePcJe/iJmrv4FpD18mbu/Dd6Ry13dad1ikxBo2ctCBtCiVXGXrPu6WWTcx1WrI1os=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
