travis:
  secure:
    BINSTAR_TOKEN: PcubCHkl9LZknoNZhh0lA4mCwoU7w31vAqARz59Zx4j/4cfQJnjhK4lh7qfHZjTC37CA01HObmUAfYvEjBzR0BkC0j7nxHqma+85yWTMF6vs9rYKqfEtuhmRmGjIBeNkwgq81Qsi/Qpkbaon1c2eekki+6IhNRApqfLL1ZhNpCfI+8RrkNbFiyM9KA9r93qBpL6vWr55sBvuYPbh4Z4v/7FBVyqc1rlDNG3frVn+vq3xN5DpwU9TwCecOLZH68+3TG0I9926sZn8yEIQCmM6glS9iiN/+XjB7smLfCKR3ZxINORpG6PgtoRKjcZ6as6jga+h/BGp0/nOcHWsV3gOUSv01wPW82YtgsFTzzIDl+urh709vD4bpY7fgHxeuzm4vHCf4xARsVOwKkhYyGb0Nopm9uwD8wzBYJ+cBZtpFcT5HJB3MDiz2gxcV47P0+MGPmCCroSLtJExaqEgf/1+gfWRm02jrSCwsDjVQhOS2nKVUYHOpYZFnqF5N3/dH/RJQs89klA4FAcMmaxu5g1p8hUxeX6mRKuKu2TNwlUQv73N4S2ZovD2JaSUAkLm0052eKMZ2E+ZJUFZyi+4VNUvr1RtqBio0iHnO0ciuRFTY1D4mMnHMuxazpg7OiYTBlkXivdpLszqx4u7/UOSrWXXwn9YLGyqQ8G/+Hfl1cduso0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
