travis:
  secure:
    BINSTAR_TOKEN: JxfbDPfYgX2Q19e2T83+hbmKGJvbfYa9qFmpUwxM4Qhs7k/AOjD2K/8aBXy7/ehogeApBtOKdNsikakvLEbyo8ZGBV7hgdloRvHze2XWp/6KwyNfI7jZ2l0w46Vu3iUcxDTJyQJ3+vNc2EPoSzXdY8THJHlayx6szoK/HkroQE3i5o1raajzPOz/4EilB959gVuYalLtpknk7BfbGwuBbh85ju0a3sTO8iFa2q0kGR1xWFGgO/fVZ/8ApaoOM3ayF7k23i0GOgzi6rKS5ogpsSB4gg3HX3Vn7RBHB9hU3ng3vyXnXx9QG0TEZFXVilMkMK10pdiSUDE3PgHQPLzvde1H7T7MZ+XjCGQoBiHKAKIB99gVwLMWBqWZf2hJz5yhqtt+YW5Lpdb6P1rCirsiHCpzXgJ7cWllTGYfYdIanAUGqTeHvi+JyeQIkL3bCoD1XgLHKEZhfS9tiudtndxMzgN0E417bD7iBQX+gwkm2v/NWRYjGSXP/otK98uvittTS6a/K0oHiUcGc4BFgRLe3Kh3EHP5b0QPt/rW471OY6bRWjrstmHanSffhaGdrolUBaRzuE9AvsV2esmQTQjJnplMCijWO4QrAb6H8+CeyLFiO3q43t8KwXR1juzjeFfID7z0R+QyWxJJv+bTB6NQdwmCUUcY5mvsWEC04aJLlaA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
