travis:
  secure:
    BINSTAR_TOKEN: Om1coMUVszzqH9EZhjLc2YVdbqq6f5uYbwsqKqPykhYgy3z/2VXn25aXFdxjsqnl4dLaaTnQFeSduZJPRlHA5I2Ze3Z454JeHzoMCXkiyGEQZR7BUhVKG2ic0IX/J8LjH91NZza0z7RHUN24m+vq4RT6WHp/tWzqOsb4ElIjBQOowQw0UIoBLlJjzlMf7zai22eN+SU22oxMcnrcymuQIn55wPNsQ/bDsUdazljEy8x336OmxBE0VtuAj+QlyQ8MNwVOJwL7mmXlI6iDQWyS8M/Td/uyEh0x//Nca34fHzV6bE4pxKZAfy1f73fUrkd808A4RFCla51TbFmMrH9L2VMJ4Hm+TOkMPVkYG8ixedZC3hTTlz5IPkPVyh+MlrlI+LqEYifo0QKzMQRYXjb23fyzfHn8ZGaHLhzrFKdna5DloPdVxuZgIy87sTnffS0+eAdH7V7hITAL7vbDQo9lTjUNCU/ETkPHmfmH6zjDeX3o8sX7/Fk//r4IWR9iX/FK/2B8KeCubslmWfWoU0UBfNozzPurSVo2ctx+0b34lc/LVnJ5mTBSkMRMcUpVAcuGCnSCDyy5JZxzekabEnmgU69BnxFzJILWH41qFn/Msf1txVK2DYjqd3h1FO+HUOcJQkMdrJkVFu23qg3MC5n+gOBCPqzMik83chTmxhbo8qs=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
