travis:
  secure:
    BINSTAR_TOKEN: YwvxBM/EaR8NeB25elr4brHiGzxkADWeF5wuKH1LYAZaeKLJqF/4qG2BLttG50OTeN/u4+5IGLMlVuvxOMz5/tumIslkOgM05/ZLei1pi8VCL4gLn0n/xQn+rrFeQQW705h9vTny1djxG8IM8MGh72lydG5+Nc92h+OvF84W5fVI1hig+x3IALr4qA8EQ3KkiAJF064qSVxnWAIW5bCYpuYxB60AptimhgiDA2FnX1d1dTs8qTi5+0z3vofRyflh+VzKr94DZLyyUSaiSGh0g9//RIFsxt/TMJnTJQm+ML8psQgxBaczLv2YNSY8Z7DJrUBJBROrgttp85IIjpsIJPfmzVt9ETGcTrI3EIr01VbI+EKZbV96SVzJ5NLCNubhSS+hzhx8yg+FDKEv2xOLxYCa6B18/cbeXOa8V4LtL/XFm4u15bGrrImLGhvJARgwXEhCgL/jkeNgrFFL1DxMm/S71He0Za2nfTXuScD1zsHyicYZsXD53sd4pf9g+3sHNnpV8Uuqkw3uKN3RJiduMb+QgfbL6aN8yjU+aV5QMSWkfhZRT3vQm/YPAgF6V4VZV7G4T6rB8g3C01rifzf9IQNVp+3dHWgX79ovUZYct9DJaZeu1CnMlS3PV8uWsf38gzSLzZM1bIDnwx61MvYIzwTT8QmzRmIvZedgRPj354U=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
